wander_node:
  ros__parameters:
    cmd_topic: /cmd_vel_raw
    vmax: 0.018
    vmax_think: 0.005
    vback: 0.006
    vback_think: 0.002
    wturn: 0.12
    wturn_think: 0.06
    slow_front: 0.18
    slow_rear: 0.12
    stop_front: 0.03
    auto_start: true
    pause_sec: 0.40
    backup_min_sec: 0.20
    backup_clear_sec: 0.30
    backup_max_sec: 6.00
    turn_sec: 5.0
